
services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    depends_on:
      - redis
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
 
  redis:
    image: redis
